= Spring Lemon Demo API Reference
Spring Lemon version 0.12
:toc: right

== Introduction

This is the API documentation of https://github.com/naturalprogrammer/lemon-demo[Spring Lemon Demo application]. This API can be called from browser based front-ends (e.g. AngularJS single page applications), as well as non-browser clients.

== Basics

Before we dive in, let's first look at a few key thing to keep in mind when using the API.

=== CORS

Your API could be accessed from multiple clients. One of those could be a JavaScript web front-end, such as an AngularJS single page application.

When developing a JavaScript web front-end, you will have two choices:

. Put it in the same project, say inside _src/main/resources/static_, and deploy both the server and the client as a single unit.
. Keep it separate, say as a _Grunt_ project, and deploy it in a different domain. For example, your API could be hosted at `example.cfapps.io`, whereas your AngularJS application could be hosted at `www.example.com`.

If you go for the second option, your JavaScript can't call your API unless you deal with the https://en.wikipedia.org/wiki/Same-origin_policy[same origin policy].

Spring Lemon uses CORS at the server side to deal with this. You just have to add a line like this in _application.properties_:

----
lemon.cors.allowed-origins: http://localhost:9000,http://www.example.com
----

You may also need a little configuration at the client side. For example, in AngularJS, you will need to set the `withCredentials` flag of https://docs.angularjs.org/api/ng/service/$http#cross-site-request-forgery-xsrf-protection[$http] service, like this:

[source,javascript]
----
angular.module('myApp', ['ngCookies', ... ])
.config(['$httpProvider', function ($httpProvider) {

    $httpProvider.defaults.withCredentials = true;
    ...
}]);
----

Refer https://github.com/naturalprogrammer/spring-lemon#documentation-and-resources[documentation and resources] for more details.

==== CSRF

_CSRF_ is a well known security vulnerability. If you do not know about it, http://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/#csrf[Spring Security reference material] explains it beautifully.

To handle CSRF, Spring Lemon sends a token to the client in each response. The token is sent as a cookie, named `XSRF-TOKEN`. Then, in each `PATCH`, `POST`, `PUT` or `DELETE` request, it expects the same token as a header named `X-XSRF-TOKEN`. An exception is thrown if the tokens do not match.

So, your client application should first send a GET request for getting the token, and then use that in POST kind of requests. Also, be aware that Spring Security removes or changes the cookie after certain events, like _logout_. Hence, after these events, your client application will again need to send some GET request and get the new token. Ping (see below) can be used for this.

When wrong CSRF token is sent, the response looks like this:

[source,json]
----
HTTP/1.1 403 Forbidden

{
"status": 403,
"error": "Forbidden",
"message": "Expected CSRF token not found. Has your session expired?",
"path": "/accessed_url"
}
----

Refer https://github.com/naturalprogrammer/spring-lemon#documentation-and-resources[documentation and resources] for more details.

===== CSRF and AngularJS

If your AngularJS client resides in the same project, say inside _src/main/resources/static_, you don't have to do anything special for CSRF. When sending a request, the https://docs.angularjs.org/api/ng/service/$http#cross-site-request-forgery-xsrf-protection[$http] service of AngularJS automatically puts the value of the `XSRF-TOKEN` cookie in a header named `X-XSRF-TOKEN`.

If you have the client as a separate project that is to be hosted separately though, you will have to add the header on your own. The easiest way to do it is to write an AngularJS _$http interceptor_, like this:

[source,javascript]
----
angular.module('myApp')
  .factory('XSRFInterceptor', function ($cookies, $log) {

    var xsrfToken;

    var XSRFInterceptor = {

      request: function(config) {

        if (xsrfToken) {
          config.headers['X-XSRF-TOKEN'] = xsrfToken;
          $log.info("X-XSRF-TOKEN being sent to server: " + xsrfToken);
        }

        return config;
      },

      response: function(response) {

        var newToken = $cookies.get('XSRF-TOKEN');

        if (newToken) {
          xsrfToken = newToken;
          $log.info("XSRF-TOKEN received from server: " + xsrfToken);
        }

        return response;
      }
    };

    return XSRFInterceptor;
  });
----

You then need to configure the interceptor as below.

[source,javascript]
----
angular.module('myApp', [...])
   .config(['$httpProvider', function ($httpProvider) {

   $httpProvider.defaults.withCredentials = true;
   $httpProvider.interceptors.push('XSRFInterceptor');
   ...
   
}]);
----

=== Handling Errors

If some request data would not comply to the business rules, the API would respond with _422 Unprocessable Entity_, with a JSON body holding field-wise error details. For example, trying to sign up with some invalid data could produce the following JSON data:

[source,json]
----
{
  "timestamp": 1494764056076,
  "status": 422,
  "error": "Unprocessable Entity",
  "exception": "javax.validation.ConstraintViolationException",
  "message": "Validation Error",
  "path": "/api/core/users",
  "errors": [
    {
      "field": "user.password",
      "code": "{com.naturalprogrammer.spring.invalid.password.size}",
      "message": "Password must be between 6 and 50 characters"
    }
  ]
}
----

Each error in `errors` above will have three fields:

1. **field**: Name of the field, or _null_ in case of a form level error.
2. **code**: The error code.
3. **message**: An internationalized message, which could vary depending on the locale of the user.

=== Format of the error data

Obviously, the format of the error JSON, its field names and codes would vary from request to request. Maintaining a documentation of each error for each request would be cumbersome. We may take that up sometime in future, but for now, the best way to know the format for any request would be to look at the actual response body by using a tool, such as the _google chrome developer tools_ or _Postman_.

=== JSON vulnerability

By default, Spring Lemon prefixes JSON responses with `)]}',\n`. This is done as a protection against the http://haacked.com/archive/2008/11/20/anatomy-of-a-subtle-json-vulnerability.aspx[JSON vulnerability]. Your client application would need to strip this `)]}',\n`. It's done automatically if you are using the https://docs.angularjs.org/api/ng/service/$http#json-vulnerability-protection[$http] service of AngularJS.

If you want to disable this protection, maybe because your API is not meant to be called from browsers, add the following line in application.properties:

```
lemon.enabled.json-prefix: false
```

== Common terms

Some terms that we would be using often in the documentation are given below.

ADMIN::
	A user having "ADMIN" in his roles collection.
	
Unverified user::
	A user having "UNVERIFIED" in his roles collection.
	
Blocked user::
	A user having "BLOCKED" in his roles collection.
	
Bad user::
	An unverified or blocked user.
	
Good user::
	A user who is not bad.
	
Bad ADMIN::
	An ADMIN who is a bad user.
	
Good ADMIN::
	An ADMIN who is a good user.

== Common Business Rules

This section documents the common business rules, which are referred from multiple places in the API documentation.

[[accessing-users]]
=== Accessing Users

==== Who is permitted to edit a User entity

===== Editing the fields
A user can be edited either by himself or a good ADMIN.

===== Adding or removing roles
. roles can only be edited by good ADMINs.
. A user can't edit his own roles even if he is a good ADMIN.

==== Confidential fields
When fetching a user (either by email or id),
. `createdDate`, `lastModifiedDate`, `password`, `verificationCode` and `forgotPasswordCode` are not returned.
. `email` and `username` are not returned if the logged in user does not have _right to edit the fields (see above)_ of the user being fetched.

[[user-constraints]]
=== User entity validation constraints

==== email
. Should not be null
. Should not be blank
. Should be between 4 and 250 characters long
. Should be well-formed email format
. Should be unique

==== password
. Should not be null
. Should not be blank
. Should be between 4 and 30 characters long

==== name
. Should not be blank
. Should be between 1 and 50 characters long

== Data structure
This section documents some data structures used in the application.

[[user-data]]
=== User data

Fetch user by email or id returns data about a user. The data looks like this:

[source,json]
----
{
    "id": 24,
    "version": 5,
    "email": "admin@example.com",
    "roles": [
        "ADMIN"
    ],
    "unverified": false,
    "blocked": false,
    "admin": true,
    "goodUser": true,
    "goodAdmin": true,
    "editable": true,
    "rolesEditable": false,
    "name": "Administrator",
    "username": "admin@example.com",
    "authorities": [
        {
            "authority": "ROLE_ADMIN"
        },
        {
            "authority": "ROLE_GOOD_ADMIN"
        },
        {
            "authority": "ROLE_GOOD_USER"
        }
    ]
}
----

Note that the fields that the logged in user wouldn't have rights to view would be omitted. Refer the https://github.com/naturalprogrammer/spring-lemon#documentation-and-resources[documentation and resources] for more details.

== Ping

Sends a GET request to the server. This is useful for fetching the CSRF cookie after an event that would have changed the CSRF token, e.g. _logout_. See the discussion on CSRF above for more details.

In summary, you may need to call this before any request that results in _CSRF mismatch_ error.

=== Request

include::{snippets}/ping/http-request.adoc[]

=== Response

include::{snippets}/ping/http-response.adoc[]

Notice how we get the CSRF cookie in the response, which is to be sent as a header in next requests.

=== Business rules

. Should return a 204 No Content with a cookie named "XSRF-TOKEN"

=== Positive test cases

. Should return a 204 No Content with a cookie named "XSRF-TOKEN"

== Ping and create session

From a browser based client, you may like to create a session so that you can use cookie based authentication. To do so, call this.

=== Request

include::{snippets}/ping-session/http-request.adoc[]

=== Response

include::{snippets}/ping-session/http-response.adoc[]

Notice the classic JSESSIONID cookie in the response.

=== Business rules

. Should return a 204 No Content with a cookie named "JSESSIONID"

=== Positive test cases

. Should return a 204 No Content with a cookie named "JSESSIONID"

== Get context

Gets useful application properties and current user data.

TIP: Call this to fetch useful application properties and current-user data when an AngularJS application starts.

=== Request

include::{snippets}/context/http-request.adoc[]

=== Response

include::{snippets}/context/http-response.adoc[]

*Fields*

include::{snippets}/context/response-fields.adoc[]

_user_ would be omitted if nobody is logged in.

Refer https://github.com/naturalprogrammer/spring-lemon#documentation-and-resources[documentation and resources] to know how to customize this response and other details.

=== Business rules

The _current-user_ data, _reCaptchaSiteKey_, and the _lemon.shared.*_ properties should be there in the response. Current-user data shouldn't include any confidential fields.

=== Positive test cases

. When not logged in, _reCaptchaSiteKey_, _lemon.shared.*_ properties should be there in the response. Current user data should be absent.
. When logged in, _reCaptchaSiteKey_, _lemon.shared.*_ properties should be there in the response. Current user data should look as above, with confidential fields omitted..

== Login

Logs the user in. To remember the user for 15 days, send a _rememberMe_ parameter set as `true`.

=== Request

include::{snippets}/login/http-request.adoc[]

*Parameters*

include::{snippets}/login/request-parameters.adoc[]

=== Response

include::{snippets}/login/http-response.adoc[]

=== Business rules

. Upon successful login, current-user data should be returned as the response.
. Giving wrong credentials should respond with `401 Aunauthorized`.
. Spring security token based http://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/#remember-me[remember-me] rules apply. Importantly,
.. A `rememberMe` cookie is returned when `rememberMe=true` is passed as a request parameter.
.. Sending the remember me cookie from a different session within 15 days would log the user in.
.. Upon logout, the cookie is reset.

=== Positive test cases

. When a good ADMIN logs in, the response should contain
.. his `name`
.. a `roles` collection with role "ADMIN"
.. `goodAdmin` as true
. When `rememberMe=true` parameter is sent, a `rememberMe` cookie is received. That cookie can be used in a different session to log the user in. Upon logging out from that session, the `rememberMe` cookie is reset.

=== Negative test cases

. Giving wrong credentials should respond with `401 Aunauthorized`.
. A wrong `rememberMe` cookie should not log a user in.

== Logout

Logs a user out.

=== Request

include::{snippets}/logout/http-request.adoc[]

=== Response

include::{snippets}/logout/http-response.adoc[]

=== Business rules

. Should log the user out, and send a 200 OK.

=== Positive test cases

. Should log the user out, and send a 200 OK.

== Switch user

=== Switching to another user

Let's a good ADMIN switch to another user. For example, a support guy can switch to another user while examining a complaint.

*Request*

include::{snippets}/switch-user/http-request.adoc[]

*Response*

include::{snippets}/switch-user/http-response.adoc[]

=== Switching back

*Request*

include::{snippets}/switch-back/http-request.adoc[]

*Response*

include::{snippets}/switch-back/http-response.adoc[]

=== Business rules

. Only good ADMINs should be able to switch.

=== Positive test cases

. A good ADMIN should be able to switch to another user, and then switch back.

=== Negative test cases

. A non-admin should not be able to switch.
. An unauthenticated user should not be able to switch.
. A bad ADMIN should not able to switch.

== Sign up

Signs up a new user and logs him in. A <<VerificationMail>> is sent to his email.

=== Request

include::{snippets}/signup/http-request.adoc[]

Add `captchaResponse` field if you want captcha validation. Sign up let's you use the new https://developers.google.com/recaptcha/[reCAPTCHA] from Google. If you use it, `captchaResponse` field should hold the captcha response. To use it,

. At the server side, set a couple of properties, as described in the https://github.com/naturalprogrammer/spring-lemon#documentation-and-resources[getting started guide].
. At the client side, for an AngularJS client, https://github.com/VividCortex/angular-recaptcha[angular-recaptcha] works great. Remember to send the captcha response in the `captchaResponse` field.

If you don't want Captcha, e.g. in a demo app, just don't provide the captcha related properties in _application.yml_.

=== Response

include::{snippets}/signup/http-response.adoc[]

=== Business rules

. Nobody should have already logged in.
. Email, password and name should be <<user-constraints,valid>>.
. The role UNVERIFIED is added to the user upon sign up.
. Password is stored encoded.
. After successful sign up
.. The user is signed in.
.. A verification mail is sent to the given email id.

=== Positive test cases

. A user should be able to sign up.
. After signing up
.. The user should have signed in.
.. His role should be UNVERIFIED.
.. A verification mail should have been sent to the user.

=== Negative test cases

Sign up will respond with errors if you try it

. After being already logged in.
. With <<user-constraints,invalid>> email, password or name.
. Using an email id which is already signed up.
. With invalid captcha.

== Resend verification mail

A verification mail is sent to users upon sign up. But, sometimes they may miss it. So, when a unverified user signs in, you may like to show him a button or something to resend the verification mail. Clicking on that should send a request to your API as below.

=== Request

include::{snippets}/resend-verification-mail/http-request.adoc[]

=== Response

include::{snippets}/resend-verification-mail/http-response.adoc[]

=== Business rules

. The user should exist.
. Current-user should have <<accessing-users,permission to edit>> the given user.
. The user should not have been verified.
. A new verification code isn't generated. The existing verification code is used instead. It's because sometimes the user might find the old mail, and try verifying with that.

=== Test cases

*Positive*

. An unverified user should be able to resend his verification code. The verificationCode of the user should not change in the process.
. A good ADMIN should be able to resend the verification mail of another unverified user.

*Negative*

. Providing unknown user id
. Trying
.. without logging in
.. logging in as a different user
.. logging in as a bad ADMIN
.. while already verified


[[VerificationMail, verification mail]]
== Verify user

After a user signs up, he receives a verification mail. The mail contains a link with an embedded `verificationCode`. Clicking on it takes the user to the front-end application, where he is first asked to login if he is not already, and then click a _verify_ button. On clicking verify, a POST request is sent as below.

=== Request

include::{snippets}/verify-user/http-request.adoc[]

*Path parameters*

include::{snippets}/verify-user/path-parameters.adoc[]

=== Response

include::{snippets}/verify-user/http-response.adoc[]

=== Business rules

. The user must have logged in.
. The user must not have already verified.
. Verification code shouldn't be blank.
. Verification code should match the code that was mailed to the user while signing up.
. Upon successful verification, the UNVERIFIED role of the user is removed, and the verification code that was stored in the user record is wiped out.
. Upon successful commit, security principal's UNVERIFIED role is removed, and it's flags such as goodUser are computed again.
. Updated current-user data is returned.

=== Positive test cases

. A new user should be able to sign in, get a verification mail, and verify himself. Check that after verification,
.. The same user is returned in the response.
.. His UNVERIFIED role is removed.
.. His verificationCode is set as null.
.. Current-user, which is the user himself, has the following changes:
.. UNVERIFIED role is removed
.. He is now a good user

=== Negative test cases

. Re-verifying after successful verification.
. Trying with wrong verification code.
. Trying without logging the user in.

[[ForgotPassword]]
== Forgot Password

When a user forgets his password, he can post a form as below.

=== Request

include::{snippets}/forgot-password/http-request.adoc[]

It would create a secret `forgotPasswordCode`, and mail the user a link including that code, looking like `https://your-front-end.com/users/{forgotPasswordCode}/reset-password`.

Clicking on the link should allow the user to <<reset_his_password>>.

=== Response

include::{snippets}/forgot-password/http-response.adoc[]

=== Business rules

. A user with the given email should exist.
. The email should be well-formed, and not null or blank.

=== Positive test cases

. Upon posting,
.. A secret code should be generated and stored in the User entity.
.. A mail containing the code should be sent to the user.

=== Negative test cases

. Providing a null, blank or not well formed email.
. Not having a user with the given email address.

[[reset_his_password, reset his password]]
== Reset password

In the <<ForgotPassword>> section, we saw how a user gets a link with a `forgotPasswordCode`. Clicking on the link should take him to a front-end form, where he should enter a new password. Upon submitting that form, a request as below should be sent.

=== Request

include::{snippets}/reset-password/http-request.adoc[]

=== Response

include::{snippets}/reset-password/http-response.adoc[]

=== Business rules

. The user should have initiated the forgot password process.
. The user shouldn't already have reset the password.
. The new password should be valid.

=== Positive test cases

. The password of the user should be updated, i.e., the user should then be able to login using the new password.

=== Negative test cases

The following tries should respond with errors:

. Trying with wrong forgotPasswordCode.
. Repeating resetting password.
. Invalid new password.

== Fetch user by email

Example use case - a good ADMIN fetching a user, maybe for changing its roles.

=== Request

include::{snippets}/fetch-user-by-email/http-request.adoc[]

=== Response

include::{snippets}/fetch-user-by-email/http-response.adoc[]

=== Business rules

. Email should be well formed, and not be blank.
. A user with the given email should exist.
. The confidential fields would be null in case the current user does not have rights to see those.

=== Positive test cases

. A user should be able to fetch his data, including the confidential email and username. But other <<accessing-users,confidential fields>> would be omitted.
. A good ADMIN should be able to fetch another user's data, including the confidential email and username. But other <<accessing-users,confidential fields>> would be omitted.
. A i) bad ADMIN, ii) non-admin or iii) anonymous user should be able to fetch another user's data. But all the <<accessing-users,confidential fields>> would be omitted.

=== Negative test cases

. Providing blank or non-well-formed email.
. Providing an unknown email id.

== Fetch user by ID

Example use case - viewing the profile of a user.

=== Request

include::{snippets}/fetch-user-by-id/http-request.adoc[]

=== Response

include::{snippets}/fetch-user-by-id/http-response.adoc[]

=== Business rules

. A user with the given id should exist.
. The <<accessing-users,confidential fields>> would be omitted in case the current-user does not have rights to see them.

=== Positive test cases

. A user should be able to fetch his data, including the confidential `email` and `username`. But other <<accessing-users,confidential fields>> would be omitted.
. A good ADMIN should be able to fetch another user's data, including the confidential `email` and `username`. But other <<accessing-users,confidential fields>> would be omitted.
. A bad ADMIN, non-admin or an anonymous user should be able to fetch another user's data. But all the <<accessing-users,confidential fields>> would be omitted.

=== Negative test cases

. Providing an unknown id.

== Update user

Updates the name and roles of a user.

=== Request

include::{snippets}/update-user/http-request.adoc[]

If you have added more updatable fields to User, they can also be updated using this request.

*What is version*

User, like all https://github.com/naturalprogrammer/spring-lemon/blob/master/src/main/java/com/naturalprogrammer/spring/lemon/domain/VersionedEntity.java[VersionedEntity], has a `version` column, which is incremented on each update.

While updating, it is first checked that the given version is equal to the version in the database record. Otherwise, it is assumed that someone else has updated the record concurrently, and the update fails. To use it, you will typically

. Along with the data to be updated, fetch the version column as well.
. When the user submits the updated data, send the version back along with the updated data.

Precisely, we are talking about optimistic locking. Refer https://github.com/naturalprogrammer/spring-lemon#documentation-and-resources[documentation and resources] for more details.

=== Response

Please note that the response is the data of the logged-in user, who isn't necessarily the updated one.

include::{snippets}/update-user/http-response.adoc[]

=== Business rules

. A user with the given `id` should exist.
. Current-user should have <<accessing-users,permission to edit>> the given user.
. `roles` will be updated only if the current-user has `permission to edit` the roles.
.. If UNVERIFIED role is removed from a user, his `verificationCode` should be set to null.
.. If UNVERIFIED role is added to a user, a `verificationCode` should also be generated, and a verification mail should be sent to the user.
. The new name <<user-constraints,should be valid>>.
. The version column should be incremented on successful update.
. The user shouldn't have been already updated concurrently, i.e. the input `version` should match the version in the database. Otherwise, expect a `409` response.
. If a user is updating himself, upon successful commit, the Security principal object is updated with the new name.

=== Positive test cases

. A non-admin user should be able to update his own name, but changes in roles should be skipped. The name of security principal object should also change in the process. The version column should be updated.
. A good ADMIN should be able to update another user's name and roles. Check that the name of security principal object should NOT change in the process by mistake.
.. When making a user UNVERIFIED, a verificationCode should be generated.
.. When making a user verified, the verificationCode should be set to null.

=== Negative test cases

. Providing an unknown id in the path.
. A non-admin trying to update the name and roles of another user.
. A bad ADMIN trying to update the name and roles of another user.
. A good ADMIN trying to change his own roles.
. Providing an invalid name.
. A change in version occuring.

== Change password

Changes the password of a user

=== Request

include::{snippets}/change-password/http-request.adoc[]

=== Response

include::{snippets}/change-password/http-response.adoc[]

=== Business rules

. A user with the given `id` should exist.
. Current user should have <<accessing-users,permission to edit>> the given user.
. `oldPassword`, `password` and `retypePassword` should not be null or blank, and should be between 6 and 30 characters long.
`oldPassword` should match the user's existing password.
. `password` and `retypePassword` should be same. (Ideally, this validation could have been left to the front-end. But, we thought to make this a server feature, for exibihiting how to code form-level custom validation.)
. If a user is changing his own password, after successful commit, he should be logged out.

=== Positive test cases

. A non-admin user should be able to change his password. After changing password, he should have been logged out.
. A good ADMIN should be able to update another user's password.

=== Negative test cases

. Providing an unknown id in the path.
. A non-admin trying to update the password of another user.
. A bad ADMIN trying to update the password of another user.
. Providing invalid passwords.
. Providing wrong old password.
. `password` and `retypePassword` not being same.

[[request-for-changing-email]]
== Requesting for changing email

A user (or a good ADMIN) can request for changing email id, by using the following request.

=== Request

include::{snippets}/request-email-change/http-request.adoc[]

On receiving such a request, an email containing a link is sent to the new email id. A secret `changeEmailCode` is embedded in the link. Clicking on the link brings the user back to the front-end, where first he should log in if he is not already. Then, he would click a button for sending the <<change-email,final email change request>> for doing the final change.

=== Response

include::{snippets}/request-email-change/http-response.adoc[]

=== Business Rules

. A user with the given `id` should exist.
. Current user should have <<accessing-users,permission to edit>> the given user.
. `password` should match the password of current-user.
. `newEmail` should not be blank, should be of a valid email format.
. `newEmail` should not already be used by any user.
. The user should be logged out after the email has changed.

=== Positive test cases

. A UNVERIFIED non-admin user should be able to request changing his email.
. A good ADMIN should be able to request changing the email of another user.

=== Negative test cases

. Providing an unknown id in the path.
. A non-admin trying to request changing email of another user.
. A bad ADMIN trying to request changing email of another user.
. Providing null password and email.
. Providing blank password and email.
. Providing invalid email.
. Providing wrong password.
. Providing non-unique email.

[[change-email]]
== Change email

When a user <<request-for-changing-email,requests for changing his email>>, a mail is sent to him, which contains a link with a `changeEmailCode` embedded. Clicking on the link brings him back to the client, where first he should login if he is not already. He then would click a button for proceeding with the change, which will send the following request to the server.

=== Request

include::{snippets}/change-email/http-request.adoc[]

*Path Parameters*

include::{snippets}/change-email/path-parameters.adoc[]

=== Response

include::{snippets}/change-email/http-response.adoc[]

The server will verify the `changeEmailCode`, and then do the change and log the user out.

=== Business rules

. The given `changeEmailCode` should not be blank.
. The given `changeEmailCode` should match that of the current user in the database.
. Before replacing `email` with `newEmail`, uniqueness should again be checked.
. On success
.. The user should be made verified if he is not already.
.. The user should be logged out.

=== Positive test cases

. An unverified user, who had requested to change his email and had received the email with the link, should be able to change his email. The `newEmail` and `changeEmailCode` should be made null after the change, and he should have got verified. Also, he should have been logged out.

=== Negative test cases

. A good ADMIN trying to post the `changeEmailCode` of another user.
. Providing wrong `changeEmailCode`.
. Trying the operation without having <<request-for-changing-email,requested>> first.
. Trying after some user registers the `newEmail` meanwhile, leaving it non unique.

== Create API Key

Creates an API key for a user, which can be used later for authorizing requests.

=== Request

include::{snippets}/create-api-key/http-request.adoc[]

=== Response

include::{snippets}/create-api-key/http-response.adoc[]

=== Business Rules

. A user with the given `id` should exist.
. Current user should have <<accessing-users,permission to edit>> the given user.

== Use API Key

The API key of a user can be used for custom token authentication, as below.

=== Request

include::{snippets}/use-api-key/http-request.adoc[]

*Headers*

include::{snippets}/use-api-key/request-headers.adoc[]

=== Response

include::{snippets}/use-api-key/http-response.adoc[]

== Remove API Key

The API key of a user can be removed as below.

=== Request

include::{snippets}/remove-api-key/http-request.adoc[]

=== Response

include::{snippets}/remove-api-key/http-response.adoc[]

=== Business Rules

. A user with the given `id` should exist.
. Current user should have <<accessing-users,permission to edit>> the given user.

