spring:
  activemq:
    broker-url: tcp://10.50.49.102:61616
    admin-broker-url: http://10.50.49.102:8161/api
    user: admin 
    password: 4QZboDsXmjMd7

queue:
  name: pps.acknowledge.notification  

sender:
  type: HTTP