server.port: ${SERVER_PORT:8083}

spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/users}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:}

  kafka:
    bootstrapAddress: ${KAFKA_URL:localhost:9092}
    consumer:
      auto-offset-reset: earliest
      group-id: guedim

user:
  topic: user-topic
  group: user-group