server:
  port: 2000

spring:
  cloud:
    gateway:
      routes:
        - id: userCmdApi-RegisterUser
          uri: http://${user.cmd.service:localhost:8081}/api/v1/registerUser
          predicates:
            - Path=/api/v1/registerUser

        - id: userCmdApi-UpdateUser
          uri: http://${user.cmd.service:localhost:8081}/api/v1/updateUser/**
          predicates:
            - Path=/api/v1/updateUser/**

        - id: userCmdApi-RemoveUser
          uri: http://${user.cmd.service:localhost:8081}/api/v1/removeUser/**
          predicates:
            - Path=/api/v1/removeUser/**

        - id: userQueryApi
          uri: http://${user.query.service:localhost:8082}/api/v1/userLookup/**
          predicates:
            - Path=/api/v1/userLookup/**

        - id: bankAccountCmdAPi-OpenAccount
          uri: http://${bank.cmd.service:localhost:9091}/api/v1/openBankAccount/**
          predicates:
            - Path=/api/v1/openBankAccount/**

        - id: bankAccountCmdAPi-DepositFund
          uri: http://${bank.cmd.service:localhost:9091}/api/v1/depositFunds/**
          predicates:
            - Path=/api/v1/depositFunds/**