# Spring
server:
  port: 9092

# mongodb and mysql
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bank
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      dll-auto: create-drop
  datasource:
    url: jdbc:mysql://${mysql.host:localhost}:3306/bank
    username: root
    password: springbankRootPsw

# security
security:
  oauth2:
    resource:
      jwt:
        key-value: springbankSigningKey